const PRIMARY_ORANGE = "#F2994A";
const PRIMARY_LIGHT_ORANGE = "#FCCF9B";

const PRIMARY_YELLOW = "#F2C94C";
const PRIMARY_DARK_GREY = "#4F4F4F";
const PRIMARY_LIGHT_GREY = "#F8F8F8";
const PRIMARY_GREY = "#78746D";
const PRIMARY_BLACK = "#3C3A36";
const PRIMARY_WHITE = "#FFFFFF";

const POINT_DARK_ORANGE = "#E46A11";

const TAG_LIGHT_PURPLE = "#9270F3";
const TAG_RED = "#EF4949";
const TAG_LIGHT_BLUE = "#65AAEA";
const TAG_BLACK = "#3C3A36";

const CARD_FONT_GREY = "#E1D6CE";

const TAB_GREY = "#CAC1C1";
const TAB_ORANGE = "#E3562A";

const SERACH_BLACK = "#333333";
const SEARCH_GREY = "#7E7A75";
const SERACH_LIGHT_GREY = "#D7D7D7";
const SERACH_RED = "#EB5757";
const SEARCH_YELLOW = "#F2C94C";
const SEARCH_DARK_GREEN = "#5BA092";

export {
  PRIMARY_ORANGE,
  PRIMARY_YELLOW,
  PRIMARY_DARK_GREY,
  PRIMARY_LIGHT_GREY,
  PRIMARY_LIGHT_ORANGE,
  PRIMARY_BLACK,
  PRIMARY_WHITE,
  POINT_DARK_ORANGE,
  TAG_LIGHT_PURPLE,
  TAG_RED,
  TAG_LIGHT_BLUE,
  TAG_BLACK,
  CARD_FONT_GREY,
  TAB_GREY,
  TAB_ORANGE,
  PRIMARY_GREY,
  SEARCH_GREY,
  SERACH_LIGHT_GREY,
  SERACH_RED,
  SEARCH_YELLOW,
  SERACH_BLACK,
  SEARCH_DARK_GREEN,
};
