const PRIMARY_ORAGNE = "#F2994A";
const PRIMARY_YELLOW = "#F2C94C";
const PRIMARY_DARK_GREY = "#4F4F4F";
const PRIMARY_LIGHT_GREY = "#F8F8F8";
const PRIMARY_GREY = "#78746D";
const PRIMARY_BLACK = "#3C3A36";
const PRIMARY_WHITE = "white";

const TAG_LIGHT_PURPLE = "#9270F3";
const TAG_RED = "#EF4949";
const TAG_LIGHT_BLUE = "#65AAEA";
const TAG_BLACK = "#3C3A36";

export {
  PRIMARY_ORAGNE,
  PRIMARY_YELLOW,
  PRIMARY_DARK_GREY,
  PRIMARY_LIGHT_GREY,
  PRIMARY_BLACK,
  PRIMARY_WHITE,
  TAG_LIGHT_PURPLE,
  TAG_RED,
  TAG_LIGHT_BLUE,
  TAG_BLACK,
  PRIMARY_GREY,
};
