const PRIMARY_BUTTON_FONT_SIZE = 15;
const SMALL_BUTTON_FONT_SIZE = 10;

const INTRO_TITLE_FONT_SIZE = 40;
const INTRO_PARAGRAPH_FONT_SIZE = 18;

const MAIN_USERNAME_FONT_SIZE = 35;
const MAIN_PARAGRAPH_FONT_SIZE = 18;
const TAG_FONT_SIZE = 12;

const BEER_NAME_FONT_SIZE = 32;
const BEER_DESCRIPTION_FONT_SIZE = 20;

const SIGN_IN_TITLE_FONT_SIZE = 30;
const SIGN_IN_DESCRIPTION_FONT_SIZE = 15;

const PROFILE_SORT_FONT_SIZE = 17;
const PROFILE_TITLE_FONT_SIZE = 25;

export {
  PRIMARY_BUTTON_FONT_SIZE,
  SMALL_BUTTON_FONT_SIZE,
  INTRO_TITLE_FONT_SIZE,
  INTRO_PARAGRAPH_FONT_SIZE,
  MAIN_USERNAME_FONT_SIZE,
  MAIN_PARAGRAPH_FONT_SIZE,
  TAG_FONT_SIZE,
  BEER_NAME_FONT_SIZE,
  BEER_DESCRIPTION_FONT_SIZE,
  SIGN_IN_TITLE_FONT_SIZE,
  SIGN_IN_DESCRIPTION_FONT_SIZE,
  PROFILE_SORT_FONT_SIZE,
  PROFILE_TITLE_FONT_SIZE,
};
