const PRIMARY_BUTTON_FONT_SIZE = 15;
const SMALL_BUTTON_FONT_SIZE = 10;

const INTRO_TITLE_FONT_SIZE = 40;
const INTRO_PARAGRAPH_FONT_SIZE = 18;

const MAIN_USERNAME_FONT_SIZE = 33;
const MAIN_PARAGRAPH_FONT_SIZE = 16;

export {
  PRIMARY_BUTTON_FONT_SIZE,
  SMALL_BUTTON_FONT_SIZE,
  INTRO_TITLE_FONT_SIZE,
  INTRO_PARAGRAPH_FONT_SIZE,
  MAIN_USERNAME_FONT_SIZE,
  MAIN_PARAGRAPH_FONT_SIZE,
};
