const PRIMARY_BUTTON_FONT_SIZE = 15;
const SMALL_BUTTON_FONT_SIZE = 10;

const INTRO_TITLE_FONT_SIZE = 40;
const INTRO_PARAGRAPH_FONT_SIZE = 18;

const TAG_FONT_SIZE = 12;

export {
  PRIMARY_BUTTON_FONT_SIZE,
  SMALL_BUTTON_FONT_SIZE,
  INTRO_TITLE_FONT_SIZE,
  INTRO_PARAGRAPH_FONT_SIZE,
  TAG_FONT_SIZE,
};
